INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('Food');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('Transportation');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('Credit Card Bills');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('Health and Fitness');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('Utilities');