DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS USER;

CREATE TABLE CATEGORY (
    CATEGORY_ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR NOT NULL
);

CREATE TABLE USER (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR NOT NULL,
    USER_MAIL_ID VARCHAR NOT NULL UNIQUE
);